// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSalesSystem.Models;

#nullable disable

namespace TicketSalesSystem.Migrations
{
    [DbContext(typeof(TicketsContext))]
    [Migration("20260126082344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketSalesSystem.Models.AccountStatus", b =>
                {
                    b.Property<string>("AccountStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("AccountStatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AccountStatusID");

                    b.ToTable("AccountStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.DescriptionImage", b =>
                {
                    b.Property<string>("ProgrammeID")
                        .HasColumnType("nchar(8)");

                    b.Property<string>("DescriptionImageID")
                        .HasColumnType("nchar(3)");

                    b.Property<string>("DescriptionImageName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ProgrammeID", "DescriptionImageID");

                    b.ToTable("DescriptionImage");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nchar(6)");

                    b.Property<string>("AccountStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Extension")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Photo")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("AccountStatusID");

                    b.HasIndex("RoleID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.EmployeeLogin", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nchar(6)");

                    b.Property<string>("Account")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("Account")
                        .IsUnique()
                        .HasFilter("[Account] IS NOT NULL");

                    b.ToTable("EmployeeLogin");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.FAQ", b =>
                {
                    b.Property<string>("FAQID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nchar(6)");

                    b.Property<string>("FAQDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAQPublishStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("FAQTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FAQTypeID")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.HasKey("FAQID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("FAQPublishStatusID");

                    b.HasIndex("FAQTypeID");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.FAQPublishStatus", b =>
                {
                    b.Property<string>("FAQPublishStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("FAQPublishStatusName")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("FAQPublishStatusID");

                    b.ToTable("FAQPublishStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.FAQType", b =>
                {
                    b.Property<string>("FAQTypeID")
                        .HasColumnType("nchar(2)");

                    b.Property<string>("FAQTypeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("FAQTypeID");

                    b.ToTable("FAQType");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Member", b =>
                {
                    b.Property<string>("MemberID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AccountStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MemberID");

                    b.HasIndex("AccountStatusID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.MemberLogin", b =>
                {
                    b.Property<string>("MemberID")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Account")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MemberID");

                    b.HasIndex("Account")
                        .IsUnique()
                        .HasFilter("[Account] IS NOT NULL");

                    b.ToTable("MemberLogin");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Order", b =>
                {
                    b.Property<string>("OrderID")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("OrderCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<DateTime?>("PaidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("PaymentTradeNO")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("SessionID")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.HasKey("OrderID");

                    b.HasIndex("MemberID");

                    b.HasIndex("OrderStatusID");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("PaymentTradeNO")
                        .IsUnique();

                    b.HasIndex("SessionID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.OrderStatus", b =>
                {
                    b.Property<string>("OrderStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("OrderStatusName")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("OrderStatusID");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Payment", b =>
                {
                    b.Property<string>("PaymentTradeNO")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PaymentDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.HasKey("PaymentTradeNO");

                    b.HasIndex("PaymentStatusID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.PaymentStatus", b =>
                {
                    b.Property<string>("PaymentStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("PaymentStatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PaymentStatusID");

                    b.ToTable("PaymentStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Place", b =>
                {
                    b.Property<string>("PlaceID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("PlaceAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlaceID");

                    b.ToTable("Place");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Programme", b =>
                {
                    b.Property<string>("ProgrammeID")
                        .HasColumnType("nchar(8)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nchar(6)");

                    b.Property<int>("LimitPerOrder")
                        .HasColumnType("int");

                    b.Property<string>("PlaceID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("ProgrammeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgrammeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProgrammeStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.Property<string>("SeatImage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProgrammeID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PlaceID");

                    b.HasIndex("ProgrammeStatusID");

                    b.ToTable("Programme");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.ProgrammeStatus", b =>
                {
                    b.Property<string>("ProgrammeStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("ProgrammeStatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ProgrammeStatusID");

                    b.ToTable("ProgrammeStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.PublicNotice", b =>
                {
                    b.Property<string>("PublicNoticeID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nchar(6)");

                    b.Property<string>("PublicNoticeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PublicNoticeStatus")
                        .HasColumnType("bit");

                    b.Property<string>("PublicNoticeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PublicNoticeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("PublicNotice");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Question", b =>
                {
                    b.Property<string>("QuestionID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuestionTypeID")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<string>("UploadFile")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("QuestionID");

                    b.HasIndex("MemberID");

                    b.HasIndex("QuestionTypeID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.QuestionType", b =>
                {
                    b.Property<string>("QuestionTypeID")
                        .HasColumnType("nchar(2)");

                    b.Property<string>("QuestionTypeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("QuestionTypeID");

                    b.ToTable("QuestionType");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Reply", b =>
                {
                    b.Property<string>("ReplyID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("nchar(6)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ReplyDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.HasKey("ReplyID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("ReplyStatusID");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.ReplyStatus", b =>
                {
                    b.Property<string>("ReplyStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("ReplyStatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ReplyStatusID");

                    b.ToTable("ReplyStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Seat", b =>
                {
                    b.Property<string>("SeatID")
                        .HasColumnType("nchar(2)");

                    b.Property<string>("SeatName")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("SeatStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.HasKey("SeatID");

                    b.HasIndex("SeatStatusID");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.SeatRow", b =>
                {
                    b.Property<string>("SeatRowID")
                        .HasColumnType("nchar(2)");

                    b.Property<string>("SeatRowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatRowID");

                    b.ToTable("SeatRow");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.SeatStatus", b =>
                {
                    b.Property<string>("SeatStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("SeatStatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SeatStatusID");

                    b.ToTable("SeatStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Session", b =>
                {
                    b.Property<string>("SessionID")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("ProgrammeID")
                        .IsRequired()
                        .HasColumnType("nchar(8)");

                    b.Property<DateTime>("SaleEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaleStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionID");

                    b.HasIndex("ProgrammeID");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Tickets", b =>
                {
                    b.Property<string>("TicketsID")
                        .HasColumnType("nchar(7)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("RefundTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowID")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<DateTime?>("ScannedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatID")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<string>("TicketsAreaID")
                        .IsRequired()
                        .HasColumnType("nchar(3)");

                    b.Property<string>("TicketsStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.HasKey("TicketsID");

                    b.HasIndex("OrderID");

                    b.HasIndex("RowID");

                    b.HasIndex("SeatID");

                    b.HasIndex("TicketsAreaID");

                    b.HasIndex("TicketsStatusID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsArea", b =>
                {
                    b.Property<string>("TicketsAreaID")
                        .HasColumnType("nchar(3)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("TicketsAreaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketsAreaStatusID")
                        .IsRequired()
                        .HasColumnType("nchar(1)");

                    b.HasKey("TicketsAreaID");

                    b.HasIndex("TicketsAreaStatusID");

                    b.ToTable("TicketsArea");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsAreaStatus", b =>
                {
                    b.Property<string>("TicketsAreaStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("TicketsAreaStatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TicketsAreaStatusID");

                    b.ToTable("TicketsAreaStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsStatus", b =>
                {
                    b.Property<string>("TicketsStatusID")
                        .HasColumnType("nchar(1)");

                    b.Property<string>("TicketsStatusName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TicketsStatusID");

                    b.ToTable("TicketsStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.DescriptionImage", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Programme", "Programme")
                        .WithMany("DescriptionImage")
                        .HasForeignKey("ProgrammeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Employee", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.AccountStatus", "AccountStatus")
                        .WithMany("Employee")
                        .HasForeignKey("AccountStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.Role", "Role")
                        .WithMany("Employee")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountStatus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.EmployeeLogin", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Employee", "Employee")
                        .WithOne("EmployeeLogin")
                        .HasForeignKey("TicketSalesSystem.Models.EmployeeLogin", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.FAQ", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Employee", "Employee")
                        .WithMany("FAQ")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.FAQPublishStatus", "FAQPublishStatus")
                        .WithMany("FAQ")
                        .HasForeignKey("FAQPublishStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.FAQType", "FAQType")
                        .WithMany("FAQ")
                        .HasForeignKey("FAQTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("FAQPublishStatus");

                    b.Navigation("FAQType");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Member", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.AccountStatus", "AccountStatus")
                        .WithMany("Member")
                        .HasForeignKey("AccountStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.MemberLogin", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Member", "Member")
                        .WithOne("MemberLogin")
                        .HasForeignKey("TicketSalesSystem.Models.MemberLogin", "MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Order", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Member", "Member")
                        .WithMany("Order")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.OrderStatus", "OrderStatus")
                        .WithMany("Order")
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Order")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.Payment", "Payment")
                        .WithOne("Order")
                        .HasForeignKey("TicketSalesSystem.Models.Order", "PaymentTradeNO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.Session", "Session")
                        .WithMany("Order")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("OrderStatus");

                    b.Navigation("Payment");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Payment", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Payment")
                        .HasForeignKey("PaymentStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Programme", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Employee", "Employee")
                        .WithMany("Programme")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.Place", "Place")
                        .WithMany("Programme")
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.ProgrammeStatus", "ProgrammeStatus")
                        .WithMany("Programme")
                        .HasForeignKey("ProgrammeStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Place");

                    b.Navigation("ProgrammeStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.PublicNotice", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Employee", "Employee")
                        .WithMany("PublicNotice")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Question", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Member", "Member")
                        .WithMany("Question")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.QuestionType", "QuestionType")
                        .WithMany("Question")
                        .HasForeignKey("QuestionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Reply", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Employee", "Employee")
                        .WithMany("Reply")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.Question", "Question")
                        .WithMany("Reply")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.ReplyStatus", "ReplyStatus")
                        .WithMany("Reply")
                        .HasForeignKey("ReplyStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Question");

                    b.Navigation("ReplyStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Seat", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.SeatStatus", "SeatStatus")
                        .WithMany("Seat")
                        .HasForeignKey("SeatStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Session", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Programme", "Programme")
                        .WithMany("Session")
                        .HasForeignKey("ProgrammeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Tickets", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.SeatRow", "Row")
                        .WithMany("Tickets")
                        .HasForeignKey("RowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.TicketsArea", "TicketsArea")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketsAreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketSalesSystem.Models.TicketsStatus", "TicketsStatus")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketsStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Row");

                    b.Navigation("Seat");

                    b.Navigation("TicketsArea");

                    b.Navigation("TicketsStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsArea", b =>
                {
                    b.HasOne("TicketSalesSystem.Models.TicketsAreaStatus", "TicketsAreaStatus")
                        .WithMany("TicketsArea")
                        .HasForeignKey("TicketsAreaStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketsAreaStatus");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.AccountStatus", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Employee", b =>
                {
                    b.Navigation("EmployeeLogin");

                    b.Navigation("FAQ");

                    b.Navigation("Programme");

                    b.Navigation("PublicNotice");

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.FAQPublishStatus", b =>
                {
                    b.Navigation("FAQ");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.FAQType", b =>
                {
                    b.Navigation("FAQ");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Member", b =>
                {
                    b.Navigation("MemberLogin");

                    b.Navigation("Order");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.OrderStatus", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Payment", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.PaymentMethod", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Place", b =>
                {
                    b.Navigation("Programme");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Programme", b =>
                {
                    b.Navigation("DescriptionImage");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.ProgrammeStatus", b =>
                {
                    b.Navigation("Programme");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Question", b =>
                {
                    b.Navigation("Reply");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.QuestionType", b =>
                {
                    b.Navigation("Question");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.ReplyStatus", b =>
                {
                    b.Navigation("Reply");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Role", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.SeatRow", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.SeatStatus", b =>
                {
                    b.Navigation("Seat");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.Session", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsArea", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsAreaStatus", b =>
                {
                    b.Navigation("TicketsArea");
                });

            modelBuilder.Entity("TicketSalesSystem.Models.TicketsStatus", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
